apiVersion: v1

kind: Pod

metadata:

  name: quota-mem-cpu-demo-2

spec:

  containers:

    - name: quota-mem-cpu-demo-ctr-2

      image: nginx

      resources:

        limits:

          memory: "200Mi"

          cpu: "800m"

        requests:

          memory: "200Mi"

          cpu: "400m"
